baseURL = "https://hugo-six-alpha.vercel.app/"
languageCode = "en-us"
title = "Blog de Educación Sexual"
theme = "ananke"


staticDir = ['static']

[params]
  featured_image = "/images/logo.png"
  twitter = "https://twitter.com/"
  instagram = "https://instagram.com/"

[taxonomies]
  tag = 'tags'
