baseURL = "https://hugo-six-alpha.vercel.app/"
languageCode = "en-us"
title = "Blog de Educación Sexual"
theme = "ananke"


staticDir = ['static']

[params]
  featured_image = "/images/logo.png"
  twitter = "https://twitter.com/"
  instagram = "https://instagram.com/"

[taxonomies]
  tag = 'tags'


[menu]
  [[menu.main]]
    identifier = 'tags'
    name = 'Etiquetas'
    pre = "<i class='fa fa-heart'></i>"
    url = '/tags/'
    weight = -110

  [[menu.main]]
    name = 'Posts'
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = '/posts/'
    weight = -100

